"""Initial migration

Revision ID: fc666b41795b
Revises: 
Create Date: 2024-09-15 22:53:31.008871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc666b41795b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('program_studi',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('keterampilan_teknis',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('preferensi_lokasi',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('perusahaan', schema=None) as batch_op:
        batch_op.alter_column('nama_perusahaan',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('lokasi_kota',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('bidang_industri',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('kriteria_teknis',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perusahaan', schema=None) as batch_op:
        batch_op.alter_column('kriteria_teknis',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('bidang_industri',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('lokasi_kota',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('nama_perusahaan',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.alter_column('preferensi_lokasi',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('keterampilan_teknis',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('program_studi',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
